version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "email-micro-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1gu82i3asgtiq"
s3_prefix = "email-micro-service"
image_repository = "293494411431.dkr.ecr.ap-southeast-1.amazonaws.com/email-microservice"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "Env=dev",
    "ParameterKey=QueueArn,ParameterValue=arn:aws:sqs:ap-southeast-1:293494411431:tf_emails.fifo"
]
