AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30

Resources:

  PhpTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 128
    Metadata:
      DockerContext: .
      Dockerfile: Dockerfile
      DockerBuildArgs:
        DEST: aws
